- name: Import postgresql sign key for Ubuntu 20.04
  tags: 
    - postgresql
  when: ansible_distribution_version == "20.04"
  apt_key:
    url: https://www.postgresql.org/media/keys/ACCC4CF8.asc
    state: present

- name: Add postgresql 14 package repository for Ubuntu 20.04
  tags: 
    - postgresql
  when: ansible_distribution_version == "20.04"
  apt_repository:
    repo: deb http://apt.postgresql.org/pub/repos/apt focal-pgdg main
    filename: pgdg
    state: present
    update_cache: yes
  register: need_package_update

- name: Install postgresql 14  pakcage on Ubuntu 20.04 and 22.04
  tags: 
    - postgresql
  apt:
    name: 
     - postgresql-14