- name: Install nginx
  tags:
    - nginx
  apt:
    name: 
     - nginx
     - nginx-extras
    state: latest

- name: Copy Nginx default config
  tags:
    - nginx
  copy:
    src: nginx.conf
    dest: /etc/nginx/nginx.conf
    mode: 0644
    owner: root
    group: root
